# Generated by Django 4.2.1 on 2023-05-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
